### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-mel-16#1]
[melissa (2).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-mel-16/files/14213243/melissa.2.pdf)

**Comment by ElisabetRD** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
